language: cpp
#before_script:
#  - sudo apt-get install libboost-test-dev -y
script:
  - cmake .
  - cmake --build .
#  - cmake --build . --target test
  - cmake --build . --target helloworld
deploy:
  provider: script
  skip_cleanup: true
  script:
  - curl -T helloworld-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb -uboydad:$BINTRAY_API_KEY "https://api.bintray.com/content/boydad/vvz/1-SimpleDebianPackage/$TRAVIS_BUILD_NUMBER/1-SimpleDebianPackage-0.0.$TRAVIS_BUILD_NUMBER-Linux.deb;deb_distribution=trusty;deb_component=main;deb_architecture=amd64;publish=1"

